FROM python:3.11-slim

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем файлы проекта в контейнер
COPY . /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt httpx pytest pymongo

# Устанавливаем Uvicorn для запуска FastAPI
RUN pip install uvicorn

# Открываем порт для приложения
EXPOSE 8000

CMD ["pytest", "test", "-v", "--disable-warnings", "--junitxml=test-results.xml"]
