FROM python:3.11-slim

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем файлы проекта в контейнер
COPY . /app

# USER gitlab-runner
# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt httpx pytest pytest-cov pymongo

RUN chmod u+x /app/test/entrypoint.sh

# Открываем порт для приложения
EXPOSE 8000

CMD ["./test/entrypoint.sh"]
